job_name: 'lim_12_0.1' # name of the job 
forecast_model: 'lim' # name of the forecast model
# ==============================
start_time: "1980010100" # YYYYMMDDHH
DA_length: 480 # in months
# ==============================
Nobs: 8 # number of observations
obs_locs: [[269,0],[278,7],[123,-6],[202,2],[210,-18],[172,1],[144,14],[124,-2]]
obs_mean_length: 12 # in months

# obs_noise: 0.1 # observation noise
obs_noise: 0.1 # variance of observation noise
obs_path : '/glade/work/zilumeng/3D_trans/data/GODAS_up150m_temp_nino_tauxy_1980_2021_kb.nc'
# ==============================
Nens: 100 # number of ensemble members
ens_path : '/glade/work/zilumeng/3D_trans/data/CMIP6_separate_model_up150m_tauxy_Nor_1850_2014_kb.nc'
model_config: '/glade/work/zilumeng/3D_trans/Code'
Ralpha: 0 # alpha * xp + (1-alpha) * xa
# ==============================
# dl model config
max_num : 10
model_path : '/glade/work/zilumeng/3D_trans/model/Geoformer_beforeTrans.pkl'
noise_path : '/glade/work/zilumeng/3D_trans/data/noise/'
noise_amp : 1.05
# ============================== 
# lim config
pc_num: 20
eof_path: "/glade/work/zilumeng/3D_trans/LIM/eof.pkl"
lim_path: "/glade/work/zilumeng/3D_trans/LIM/lim/lim_0_3.pkl"
# ==============================
save_path : '/glade/work/zilumeng/3D_trans/Da/res_end/'
# ==============================
post_path : '/glade/work/zilumeng/3D_trans/Da/res_end/'

